##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: robot/iiwa_allegro_description/configuration/bimanual_test.usd
    usd_robot_root: "/robot"
    isaac_usd_path: robot/iiwa_allegro_description/configuration/bimanual_test_sim.usd
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: robot/iiwa_allegro_description/bimanual_iiwa_test.urdf
    asset_root_path: robot/iiwa_allegro_description
    
    base_link: "world"
    ee_link: "reflex_palm_link"
    link_names: ["reflex_palm_link", "robotiq_grasp_frame"]
    lock_joints: 
      {
        "reflex_preshape_joint_1": 0.0,
        "reflex_proximal_joint_1": 0.0,
        "reflex_preshape_joint_2": 0.0,
        "reflex_proximal_joint_2": 0.0,
        "reflex_proximal_joint_3": 0.0,
      }
    extra_links: null
    
    collision_link_names: 
      - world
      - left_lbr_link_0
      - left_lbr_link_1
      - left_lbr_link_2
      - left_lbr_link_3
      - left_lbr_link_4
      - left_lbr_link_5
      - left_lbr_link_6
      - left_lbr_link_7
      - reflex2_to_iiwa_mount
      - reflex_proximal_link_1
      - reflex_flex_link_1
      - reflex_distal_link_1
      - reflex_proximal_link_2
      - reflex_flex_link_2
      - reflex_distal_link_2
      - reflex_proximal_link_3
      - reflex_flex_link_3
      - reflex_distal_link_3
      - right_lbr_link_0
      - right_lbr_link_1
      - right_lbr_link_2
      - right_lbr_link_3
      - right_lbr_link_4
      - right_lbr_link_5
      - right_lbr_link_6
      - right_lbr_link_7
      - robotiq_to_lbr_mount
      - robotiq_link


    collision_spheres: spheres/bimanual_test.yml 
    collision_sphere_buffer: 0.005 
    extra_collision_spheres: {}
    self_collision_ignore: 
      {
        world: [left_lbr_link_0, left_lbr_link_1, right_lbr_link_0, right_lbr_link_1],
        left_lbr_link_0: [left_lbr_link_1, left_lbr_link_2],
        left_lbr_link_1: [left_lbr_link_2, left_lbr_link_3],
        left_lbr_link_2: [left_lbr_link_3, left_lbr_link_4],
        left_lbr_link_3: [left_lbr_link_4, left_lbr_link_5],
        left_lbr_link_4: [left_lbr_link_5, left_lbr_link_6],
        left_lbr_link_5: [left_lbr_link_6, left_lbr_link_7],
        left_lbr_link_6: 
          [
            left_lbr_link_7, 
            left_lbr_link_ee,
            reflex2_to_iiwa_mount, 
            reflex2_extra_shell, 
            reflex_shell_link,
            reflex_pad_link,
            reflex_palm_link,
          ],
        left_lbr_link_7: 
          [
            left_lbr_link_ee, 
            reflex2_to_iiwa_mount, 
            reflex2_extra_shell, 
            reflex_shell_link,
            reflex_pad_link,
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        left_lbr_link_ee: 
          [
            reflex2_to_iiwa_mount, 
            reflex2_extra_shell, 
            reflex_shell_link,
            reflex_pad_link,
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex2_to_iiwa_mount: 
          [
            reflex2_extra_shell, 
            reflex_shell_link,
            reflex_pad_link,
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex2_extra_shell: 
          [
            reflex_shell_link,
            reflex_pad_link,
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_shell_link: 
          [
            reflex_pad_link,
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_pad_link:   
          [
            reflex_palm_link,
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_palm_link:  
          [
            reflex_swivel_link_1,
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_swivel_link_1: 
          [
            reflex_proximal_link_1,
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_link_1: 
          [
            reflex_proximal_pad_link_1,
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_pad_link_1: 
          [
            reflex_flex_link_1,
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_flex_link_1: 
          [
            reflex_distal_link_1,
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_distal_link_1: 
          [
            reflex_distal_pad_link_1,
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_distal_pad_link_1: 
          [
            reflex_swivel_link_2,
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_swivel_link_2: 
          [
            reflex_proximal_link_2,  
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_link_2: 
          [
            reflex_proximal_pad_link_2,
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_pad_link_2: 
          [
            reflex_flex_link_2,
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_flex_link_2: 
          [
            reflex_distal_link_2,
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_distal_link_2: 
          [
            reflex_distal_pad_link_2,
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_distal_pad_link_2: 
          [
            reflex_proximal_link_3,
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_link_3: 
          [
            reflex_proximal_pad_link_3,
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_proximal_pad_link_3: 
          [
            reflex_flex_link_3,
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_flex_link_3: 
          [
            reflex_distal_link_3,
            reflex_distal_pad_link_3,
          ],
        reflex_distal_link_3: 
          [
            reflex_distal_pad_link_3,
          ],
        right_lbr_link_0: [right_lbr_link_1, right_lbr_link_2],
        right_lbr_link_1: [right_lbr_link_2, right_lbr_link_3],
        right_lbr_link_2: [right_lbr_link_3, right_lbr_link_4],
        right_lbr_link_3: [right_lbr_link_4, right_lbr_link_5],
        right_lbr_link_4: [right_lbr_link_5, right_lbr_link_6],
        right_lbr_link_5: [right_lbr_link_6, right_lbr_link_7],
        right_lbr_link_6: [right_lbr_link_7, robotiq_to_lbr_mount, robotiq_link],
        right_lbr_link_7: [robotiq_to_lbr_mount, robotiq_link],
        robotiq_to_lbr_mount: [robotiq_link],
      } 
    self_collision_buffer: 
      left_lbr_link_0: 0.0
      left_lbr_link_1: 0.0
      left_lbr_link_2: 0.0
      left_lbr_link_3: 0.0
      left_lbr_link_4: 0.0
      left_lbr_link_5: 0.0
      left_lbr_link_6: 0.0
      left_lbr_link_7: 0.0
      left_lbr_link_ee: 0.0
      reflex_shell_link: 0.0
      reflex_pad_link: 0.0
      reflex_swivel_link_1: 0.0
      reflex_proximal_link_1: 0.0
      reflex_proximal_pad_link_1: 0.0
      reflex_flex_link_1: 0.0
      reflex_distal_link_1: 0.0
      reflex_distal_pad_link_1: 0.0
      reflex_swivel_link_2: 0.0
      reflex_proximal_link_2: 0.0
      reflex_proximal_pad_link_2: 0.0
      reflex_flex_link_2: 0.0
      reflex_distal_link_2: 0.0
      reflex_distal_pad_link_2: 0.0
      reflex_proximal_link_3: 0.0
      reflex_proximal_pad_link_3: 0.0
      reflex_flex_link_3: 0.0
      reflex_distal_link_3: 0.0
      reflex_distal_pad_link_3: 0.0
      reflex2_to_iiwa_mount: 0.0
      reflex2_extra_shell: 0.0
      right_lbr_link_0: 0.0
      right_lbr_link_1: 0.0
      right_lbr_link_2: 0.0
      right_lbr_link_3: 0.0
      right_lbr_link_4: 0.0
      right_lbr_link_5: 0.0
      right_lbr_link_6: 0.0
      right_lbr_link_7: 0.0
      robotiq_to_lbr_mount: 0.0
      robotiq_link: 0.0

    use_global_cumul: True
    mesh_link_names: 
      - left_lbr_link_0
      - left_lbr_link_1
      - left_lbr_link_2
      - left_lbr_link_3
      - left_lbr_link_4
      - left_lbr_link_5
      - left_lbr_link_6
      - left_lbr_link_7
      - reflex_shell_link
      - reflex_pad_link
      - reflex_swivel_link_1
      - reflex_proximal_link_1
      - reflex_proximal_pad_link_1
      - reflex_flex_link_1
      - reflex_distal_link_1
      - reflex_distal_pad_link_1
      - reflex_swivel_link_2
      - reflex_proximal_link_2
      - reflex_proximal_pad_link_2
      - reflex_flex_link_2
      - reflex_distal_link_2
      - reflex_distal_pad_link_2
      - reflex_proximal_link_3
      - reflex_proximal_pad_link_3
      - reflex_flex_link_3
      - reflex_distal_link_3
      - reflex_distal_pad_link_3
      - reflex2_to_iiwa_mount
      - reflex2_extra_shell
      - right_lbr_link_0
      - right_lbr_link_1
      - right_lbr_link_2
      - right_lbr_link_3
      - right_lbr_link_4
      - right_lbr_link_5
      - right_lbr_link_6
      - right_lbr_link_7
      - robotiq_to_lbr_mount
      - robotiq_link
    external_asset_path: null 

    cspace:
      joint_names: 
        [
          "left_lbr_A1", 
          "left_lbr_A2", 
          "left_lbr_A3", 
          "left_lbr_A4", 
          'left_lbr_A5', 
          "left_lbr_A6", 
          "left_lbr_A7", 
          "reflex_preshape_joint_1",
          "reflex_proximal_joint_1",
          "reflex_preshape_joint_2",
          "reflex_proximal_joint_2",
          "reflex_proximal_joint_3",
          "right_lbr_A1", 
          "right_lbr_A2", 
          "right_lbr_A3", 
          "right_lbr_A4", 
          'right_lbr_A5', 
          "right_lbr_A6", 
          "right_lbr_A7", 
        ] 
      retract_config: 
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      null_space_weight: 
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      cspace_distance_weight: 
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
      max_jerk: 500.0
      max_acceleration: 15.0
