##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: robot/iiwa_allegro_description/configuration/bimanual_robotiq_flat.usd
    usd_robot_root: "/robot"
    isaac_usd_path: robot/iiwa_allegro_description/configuration/bimanual_robotiq_flat_sim.usd
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: robot/iiwa_allegro_description/bimanual_robotiq_flat.urdf
    asset_root_path: robot/iiwa_allegro_description
    
    base_link: "world"
    ee_link: "left_robotiq_link"
    link_names: ["left_robotiq_link", "right_robotiq_link"]
    lock_joints: null
    extra_links: {"attached_object":{"parent_link_name": "left_robotiq_link", "link_name": "attached_object", 
                  "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED", "joint_name": "attach_joint"}}
    
    collision_link_names: 
      - world
      - right_lbr_link_0
      - right_lbr_link_1
      - right_lbr_link_2
      - right_lbr_link_3
      - right_lbr_link_4
      - right_lbr_link_5
      - right_lbr_link_6
      - right_lbr_link_7
      - right_robotiq_to_lbr_mount
      - right_robotiq_link
      - left_lbr_link_0
      - left_lbr_link_1
      - left_lbr_link_2
      - left_lbr_link_3
      - left_lbr_link_4
      - left_lbr_link_5
      - left_lbr_link_6
      - left_lbr_link_7
      - left_robotiq_to_lbr_mount
      - left_robotiq_link
      - attached_object


    collision_spheres: spheres/bimanual_robotiq.yml 
    collision_sphere_buffer: 0.005 
    extra_collision_spheres: {"attached_object": 10}
    self_collision_ignore: 
      {
        world: [right_lbr_link_0, right_lbr_link_1, right_lbr_link_0, right_lbr_link_1],
        right_lbr_link_0: [right_lbr_link_1, right_lbr_link_2],
        right_lbr_link_1: [right_lbr_link_2, right_lbr_link_3],
        right_lbr_link_2: [right_lbr_link_3, right_lbr_link_4],
        right_lbr_link_3: [right_lbr_link_4, right_lbr_link_5],
        right_lbr_link_4: [right_lbr_link_5, right_lbr_link_6],
        right_lbr_link_5: [right_lbr_link_6, right_lbr_link_7, attached_object],
        right_lbr_link_6: [right_lbr_link_7, right_robotiq_to_lbr_mount, right_robotiq_link, attached_object],
        right_lbr_link_7: [right_robotiq_to_lbr_mount, right_robotiq_link, attached_object],
        right_robotiq_to_lbr_mount: [right_robotiq_link, attached_object],
        left_lbr_link_0: [left_lbr_link_1, left_lbr_link_2],
        left_lbr_link_1: [left_lbr_link_2, left_lbr_link_3],
        left_lbr_link_2: [left_lbr_link_3, left_lbr_link_4],
        left_lbr_link_3: [left_lbr_link_4, left_lbr_link_5],
        left_lbr_link_4: [left_lbr_link_5, left_lbr_link_6],
        left_lbr_link_5: [left_lbr_link_6, left_lbr_link_7],
        left_lbr_link_6: [left_lbr_link_7, left_robotiq_to_lbr_mount, left_robotiq_link],
        left_lbr_link_7: [left_robotiq_to_lbr_mount, left_robotiq_link],
        left_robotiq_to_lbr_mount: [left_robotiq_link],
      } 
    self_collision_buffer: 
      right_lbr_link_0: 0.0
      right_lbr_link_1: 0.0
      right_lbr_link_2: 0.0
      right_lbr_link_3: 0.0
      right_lbr_link_4: 0.0
      right_lbr_link_5: 0.0
      right_lbr_link_6: 0.0
      right_lbr_link_7: 0.0
      right_robotiq_to_lbr_mount: 0.0
      right_robotiq_link: 0.0
      left_lbr_link_0: 0.0
      left_lbr_link_1: 0.0
      left_lbr_link_2: 0.0
      left_lbr_link_3: 0.0
      left_lbr_link_4: 0.0
      left_lbr_link_5: 0.0
      left_lbr_link_6: 0.0
      left_lbr_link_7: 0.0
      left_robotiq_to_lbr_mount: 0.0
      left_robotiq_link: 0.0
      attached_object: 0.0

    use_global_cumul: True
    mesh_link_names: 
      - right_lbr_link_0
      - right_lbr_link_1
      - right_lbr_link_2
      - right_lbr_link_3
      - right_lbr_link_4
      - right_lbr_link_5
      - right_lbr_link_6
      - right_lbr_link_7
      - right_robotiq_to_lbr_mount
      - right_robotiq_link
      - left_lbr_link_0
      - left_lbr_link_1
      - left_lbr_link_2
      - left_lbr_link_3
      - left_lbr_link_4
      - left_lbr_link_5
      - left_lbr_link_6
      - left_lbr_link_7
      - left_robotiq_to_lbr_mount
      - left_robotiq_link
    external_asset_path: null 

    cspace:
      joint_names: 
        [
          "right_lbr_A1", 
          "right_lbr_A2", 
          "right_lbr_A3", 
          "right_lbr_A4", 
          'right_lbr_A5', 
          "right_lbr_A6", 
          "right_lbr_A7", 
          "left_lbr_A1", 
          "left_lbr_A2", 
          "left_lbr_A3", 
          "left_lbr_A4", 
          'left_lbr_A5', 
          "left_lbr_A6", 
          "left_lbr_A7", 
        ] 
      retract_config: 
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      null_space_weight: 
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      cspace_distance_weight: 
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
      max_jerk: 500.0
      max_acceleration: 15.0
