##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: robot/dvrk_description/configuration/dvrk.usd
    usd_robot_root: "/robot"
    isaac_usd_path: robot/iiwa_allegro_description/configuration/dvrk_sim.usd
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: robot/dvrk_description/dvrk.urdf
    asset_root_path: robot/dvrk_description

    base_link: "world"
    ee_link: "psm_tool_yaw_link"
    link_names: null
    lock_joints: {'psm_tool_gripper1_joint': 0.0, 'psm_tool_gripper2_joint': 0.0}

    extra_links: null
    extra_collision_spheres: null

    collision_link_names: ['psm_base_link', 'psm_yaw_link', 'psm_pitch_back_link', 'psm_pitch_bottom_link', 'psm_pitch_end_link',
                          'psm_main_insertion_link', 'psm_tool_roll_link', 'psm_tool_pitch_link', 'psm_tool_yaw_link',
                          'psm_tool_gripper1_link', 'psm_tool_gripper2_link']

    collision_spheres: spheres/dvrk.yml

    collision_sphere_buffer: 0.005

    self_collision_ignore: {
      "psm_base_link": ['psm_yaw_link', 'psm_pitch_back_link', 'psm_pitch_bottom_link'],
      "psm_yaw_link": ["psm_pitch_back_link", 'psm_pitch_bottom_link'],
      "psm_pitch_back_link": ["psm_pitch_bottom_link", 'psm_pitch_end_link'],
      "psm_pitch_bottom_link": ["psm_pitch_end_link", 'psm_main_insertion_link'],
      "psm_pitch_end_link": ["psm_main_insertion_link", 'psm_tool_roll_link', 'psm_tool_pitch_link', 'psm_tool_yaw_link', 'psm_tool_gripper1_link', 'psm_tool_gripper2_link'],
      "psm_main_insertion_link": ['psm_tool_roll_link', 'psm_tool_pitch_link', 'psm_tool_yaw_link', 'psm_tool_gripper1_link', 'psm_tool_gripper2_link'],
      "psm_tool_roll_link": ['psm_tool_pitch_link', 'psm_tool_yaw_link', 'psm_tool_gripper1_link', 'psm_tool_gripper2_link'],
      "psm_tool_pitch_link": ['psm_tool_yaw_link', 'psm_tool_gripper1_link', 'psm_tool_gripper2_link'],
      "psm_tool_yaw_link": ['psm_tool_gripper1_link', 'psm_tool_gripper2_link'],
      "psm_tool_gripper1_link": ['psm_tool_gripper2_link'],
      }
    self_collision_buffer: {
      'psm_base_link': 0.0,
      'psm_yaw_link': 0.0,
      'psm_pitch_back_link': 0.0,
      'psm_pitch_bottom_link': 0.0,
      'psm_pitch_end_link': 0.0,
      'psm_main_insertion_link': 0.0,
      'psm_tool_roll_link': 0.0,
      'psm_tool_pitch_link': 0.0,
      'psm_tool_yaw_link': 0.0,
      'psm_tool_gripper1_link': 0.0,
      'psm_tool_gripper2_link': 0.0,
      }

    use_global_cumul: True
    mesh_link_names:  ['psm_base_link','psm_yaw_link', 'psm_pitch_back_link', 'psm_pitch_bottom_link', 'psm_pitch_end_link',
                        'psm_main_insertion_link', 'psm_tool_roll_link', 'psm_tool_pitch_link', 'psm_tool_yaw_link',
                      'psm_tool_gripper1_link', 'psm_tool_gripper2_link']

    cspace:
      joint_names: ['psm_yaw_joint', 'psm_pitch_back_joint', 'psm_pitch_bottom_joint', 'psm_pitch_end_joint', 'psm_main_insertion_joint', 
                    'psm_tool_roll_joint', 'psm_tool_pitch_joint', 'psm_tool_yaw_joint', 'psm_tool_gripper1_joint', 'psm_tool_gripper2_joint']
      retract_config:  [0.0, 0.0081, 0.007, 0.0014, 0.0653, -0.0, -0.0002, 0.0, 0.0, 0.0]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 10000.0
      max_acceleration: 10.0
