##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: robot/iiwa_allegro_description/configuration/iiwa_nohand.usd
    usd_robot_root: "/robot"
    isaac_usd_path: robot/iiwa_allegro_description/configuration/iiwa_nohand_sim.usd
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: robot/iiwa_allegro_description/iiwa_nohand.urdf
    asset_root_path: robot/iiwa_allegro_description
    
    base_link: "world"
    ee_link: "iiwa_link_ee"
    link_names: null
    lock_joints: null
    extra_links: null

    
    collision_link_names: 
      - robot_table_link
      - iiwa_link_0
      - iiwa_link_1
      - iiwa_link_2
      - iiwa_link_3
      - iiwa_link_4
      - iiwa_link_5
      - iiwa_link_6
      - iiwa_link_7
      - iiwa_link_ee
    collision_spheres: spheres/iiwa_nohand.yml 
    collision_sphere_buffer: 0.005 
    extra_collision_spheres: {}
    self_collision_ignore: 
      {
        robot_table_link: [iiwa_link_0],
        iiwa_link_0: [iiwa_link_1, iiwa_link_2],
        iiwa_link_1: [iiwa_link_2, iiwa_link_3],
        iiwa_link_2: [iiwa_link_3, iiwa_link_4],
        iiwa_link_3: [iiwa_link_4, iiwa_link_5],
        iiwa_link_4: [iiwa_link_5, iiwa_link_6],
        iiwa_link_5: [iiwa_link_6, iiwa_link_7],
        iiwa_link_6: [iiwa_link_7, iiwa_link_ee],
        iiwa_link_7: [iiwa_link_ee],
      } 
    self_collision_buffer: 
      iiwa_link_0: 0.0
      iiwa_link_1: 0.0
      iiwa_link_2: 0.0
      iiwa_link_3: 0.0
      iiwa_link_4: 0.0
      iiwa_link_5: 0.0
      iiwa_link_6: 0.0
      iiwa_link_7: 0.0
      iiwa_link_ee: 0.0
      robot_table_link: 0.01

    use_global_cumul: True
    mesh_link_names: 
      - robot_table_link
      - iiwa_link_0
      - iiwa_link_1
      - iiwa_link_2
      - iiwa_link_3
      - iiwa_link_4
      - iiwa_link_5
      - iiwa_link_6
      - iiwa_link_7
    external_asset_path: null 

    cspace:
      joint_names: 
        [
          "iiwa_joint_1", 
          "iiwa_joint_2", 
          "iiwa_joint_3", 
          "iiwa_joint_4", 
          'iiwa_joint_5', 
          "iiwa_joint_6", 
          "iiwa_joint_7", 
        ] 
      retract_config: 
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      null_space_weight: 
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      cspace_distance_weight: 
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
      max_jerk: 500.0
      max_acceleration: 15.0
