##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

collision_spheres:
    lbr_link_0:
        - "center": [0.0, 0.0, 0.11]
          "radius": 0.11
    lbr_link_1:
        - "center": [0.0, -0.04, 0.2]
          "radius": 0.08
    lbr_link_2:
        - "center": [0.0, 0.07, 0.0]
          "radius": 0.075
    lbr_link_3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.08
        - "center": [0.0, 0.045, 0.18]
          "radius": 0.07
    lbr_link_4:
        - "center": [0.0, -0.06, 0.01]
          "radius": 0.07
    lbr_link_5:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.07
    lbr_link_6:
        - "center": [0.0, 0.03, 0.0]
          "radius": 0.058
        - "center": [0.0, 0.08, -0.02]
          "radius": 0.063
    lbr_link_7:
        - "center": [0.0, 0.0, 0.01]
          "radius": 0.045
    reflex2_to_iiwa_mount: 
        - "center": [0.02, -0.005, 0.04]
          "radius": 0.05
        - "center": [-0.02, -0.005, 0.04]
          "radius": 0.05
    reflex_proximal_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.013
    reflex_flex_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.007
    reflex_distal_link_1: 
        - "center": [0.0375, 0.0, 0.0]
          "radius": 0.007
    reflex_proximal_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.013
    reflex_flex_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.007
    reflex_distal_link_2: 
        - "center": [0.0375, 0.0, 0.0]
          "radius": 0.007
    reflex_proximal_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.013
    reflex_flex_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.007
    reflex_distal_link_3: 
        - "center": [0.0375, 0.0, 0.0]
          "radius": 0.007
    